### ISSUE TITLE
python 3.6 and 3.7 

### ISSUE THREAD

**Issue by duongkstn** [ngthuong45/vietnam-number#2]
mình chạy code các bạn và chạy được trên python 3.6 và python 3.7, bạn có thể mở rộng requirements được không, vì phần lớn người ta hay dùng 3.6 và 3.7 á

**Comment by ngthuong45** [comment]
cảm ơn bạn đã gửi phản hồi nha. Mình sẽ thêm yêu cầu của bạn vào bản phát hành sắp tới.

**Comment by ngthuong45** [comment]
@duongkstn phiên bản v1.0.3 đã hỗ trợ cho python 3.6 trở lên bạn cài đặt và test lại nha. Phản hồi lại cho mình nếu có bất cứ lỗi nào nhé!

**Comment by ngthuong45** [comment]
@duongkstn nếu không có lỗi gì khác mình xin phép được đóng issues này lại.

**Comment by duongkstn** [comment]
@ngthuong45 à ừ thôi bạn test đi nhé :)), mình chưa có tgian test hộ :)
