### ISSUE TITLE
Vấn đề chuyển đổi số gồm nhiều số 0 sang từ

### ISSUE THREAD

**Issue by tunga99937** [ngthuong45/vietnam-number#3]
Tôi đã dùng thử thư viện của bạn nhưng tồi đã gặp trường hợp sau đây:
n2w('1000') cho ra kết quả là 'một nghìn không trăm'.
Đáng nhẽ trường hợp này chỉ nên cho ra kết quả là 1000. Mong bạn check lại.

**Comment by congnt-timevn** [comment]
Mình cũng gặp trường hợp này, mong bạn sớm fix.

Cảm ơn bạn!

**Comment by BinhMinhs10** [comment]
40680000000 cho ra kết qủa "bốn mươi tỷ sáu trăm tám mươi triệu không trăm nghìn không trăm"
mong bạn fix sớm

**Comment by ngthuong45** [comment]
fix bug with #4
